using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EvenFibonacciNumbers
{
    class Program
    {
        static void Main(string[] args)
        {

            //Project Euler - Problem 2 
            //Even Fibonacci numbers 
            //Each new term in the Fibonacci sequence is generated by adding the previous two terms.
            //By starting with 1 and 2, the first 10 terms will be:
            //1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
            //By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
            //find the sum of the even-valued terms.

            int num1 = 1;
            int num2 = 2;
            int nextNum = 3;
            int total = 2;

            while (nextNum < 4000000)
            {
                if (nextNum % 2 == 0)
                {
                    total += nextNum;
                }
                num1 = num2;
                num2 = nextNum;
                nextNum = num1 + num2;
            }

            Console.WriteLine(total);
            Console.ReadKey(true);

            //answer: 4613732
        }
    }
}
